# Common errors
API_NOT_IMPLEMENTED_ERROR = "API_NOT_IMPLEMENTED_ERROR"
CANNOT_PERFORM_THIS_ACTION_WITH_GIVEN_SERVICE_TYPE_ERROR = (
    "CANNOT_PERFORM_THIS_ACTION_WITH_GIVEN_SERVICE_TYPE_ERROR"
)
GENERAL_ERROR = "GENERAL_ERROR"
OBJECT_DOES_NOT_EXIST_ERROR = "OBJECT_DOES_NOT_EXIST_ERROR"
PERMISSION_DENIED_ERROR = "PERMISSION_DENIED_ERROR"
PROFILE_HAS_NO_PRIMARY_EMAIL_ERROR = "PROFILE_HAS_NO_PRIMARY_EMAIL_ERROR"
PROFILE_DOES_NOT_EXIST_ERROR = "PROFILE_DOES_NOT_EXIST_ERROR"
TOKEN_EXPIRED_ERROR = "TOKEN_EXPIRED_ERROR"

# Profile specific errors
CONNECTED_SERVICE_DELETION_FAILED_ERROR = "CONNECTED_SERVICE_DELETION_FAILED_ERROR"
CONNECTED_SERVICE_DELETION_NOT_ALLOWED_ERROR = (
    "CONNECTED_SERVICE_DELETION_NOT_ALLOWED_ERROR"
)
INVALID_EMAIL_FORMAT_ERROR = "INVALID_EMAIL_FORMAT"
PROFILE_MUST_HAVE_ONE_PRIMARY_EMAIL = "PROFILE_MUST_HAVE_ONE_PRIMARY_EMAIL"
SERVICE_CONNECTION_ALREADY_EXISTS_ERROR = "SERVICE_CONNECTION_ALREADY_EXISTS_ERROR"

# Youth Profile specific errors
APPROVER_EMAIL_CANNOT_BE_EMPTY_FOR_MINORS_ERROR = (
    "APPROVER_EMAIL_CANNOT_BE_EMPTY_FOR_MINORS_ERROR"
)
CANNOT_CREATE_YOUTH_PROFILE_IF_UNDER_13_YEARS_OLD_ERROR = (
    "CANNOT_CREATE_YOUTH_PROFILE_IF_UNDER_13_YEARS_OLD_ERROR"
)
CANNOT_RENEW_YOUTH_PROFILE_ERROR = "CANNOT_RENEW_YOUTH_PROFILE_ERROR"
CANNOT_SET_PHOTO_USAGE_PERMISSION_IF_UNDER_15_YEARS_ERROR = (
    "CANNOT_SET_PHOTO_USAGE_PERMISSION_IF_UNDER_15_YEARS_ERROR"
)
