# Common errors
GENERAL_ERROR = "GENERAL_ERROR"
OBJECT_DOES_NOT_EXIST_ERROR = "OBJECT_DOES_NOT_EXIST_ERROR"
INVALID_EMAIL_FORMAT_ERROR = "INVALID_EMAIL_FORMAT"
PERMISSION_DENIED_ERROR = "PERMISSION_DENIED_ERROR"
PROFILE_DOES_NOT_EXIST_ERROR = "PROFILE_DOES_NOT_EXIST_ERROR"
TOKEN_EXPIRED_ERROR = "TOKEN_EXPIRED_ERROR"
VALIDATION_ERROR = "VALIDATION_ERROR"
JWT_AUTHENTICATION_ERROR = "JWT_AUTHENTICATION_ERROR"
DATA_CONFLICT_ERROR = "DATA_CONFLICT_ERROR"

# Profile specific errors
CONNECTED_SERVICE_DATA_QUERY_FAILED_ERROR = "CONNECTED_SERVICE_DATA_QUERY_FAILED_ERROR"
CONNECTED_SERVICE_DELETION_FAILED_ERROR = "CONNECTED_SERVICE_DELETION_FAILED_ERROR"
CONNECTED_SERVICE_DELETION_NOT_ALLOWED_ERROR = (
    "CONNECTED_SERVICE_DELETION_NOT_ALLOWED_ERROR"
)
MISSING_GDPR_API_TOKEN_ERROR = "MISSING_GDPR_API_TOKEN_ERROR"
SERVICE_DOES_NOT_EXIST_ERROR = "SERVICE_DOES_NOT_EXIST_ERROR"
SERVICE_CONNECTION_ALREADY_EXISTS_ERROR = "SERVICE_CONNECTION_ALREADY_EXISTS_ERROR"
SERVICE_CONNECTION_DOES_NOT_EXIST_ERROR = "SERVICE_CONNECTION_DOES_NOT_EXIST_ERROR"
SERVICE_NOT_IDENTIFIED_ERROR = "SERVICE_NOT_IDENTIFIED_ERROR"
PROFILE_ALREADY_EXISTS_FOR_USER_ERROR = "PROFILE_ALREADY_EXISTS_FOR_USER_ERROR"
PROFILE_MUST_HAVE_PRIMARY_EMAIL = "PROFILE_MUST_HAVE_PRIMARY_EMAIL"
INSUFFICIENT_LOA_ERROR = "INSUFFICIENT_LOA_ERROR"
FIELD_NOT_ALLOWED_ERROR = "FIELD_NOT_ALLOWED_ERROR"

# Service specific GDPR errors
SERVICE_GDPR_API_REQUEST_ERROR = "SERVICE_GDPR_API_REQUEST_ERROR"
SERVICE_GDPR_API_UNKNOWN_ERROR = "SERVICE_GDPR_API_UNKNOWN_ERROR"
