# Common errors
GENERAL_ERROR = "GENERAL_ERROR"
PERMISSION_DENIED_ERROR = "PERMISSION_DENIED_ERROR"
OBJECT_DOES_NOT_EXIST_ERROR = "OBJECT_DOES_NOT_EXIST_ERROR"
TOKEN_EXPIRED_ERROR = "TOKEN_EXPIRED_ERROR"
PROFILE_DOES_NOT_EXIST_ERROR = "PROFILE_DOES_NOT_EXIST_ERROR"
API_NOT_IMPLEMENTED_ERROR = "API_NOT_IMPLEMENTED_ERROR"
PROFILE_HAS_NO_PRIMARY_EMAIL_ERROR = "PROFILE_HAS_NO_PRIMARY_EMAIL_ERROR"

# Profile specific errors
SERVICE_CONNECTION_ALREADY_EXISTS_ERROR = "SERVICE_CONNECTION_ALREADY_EXISTS_ERROR"
CANNOT_DELETE_PROFILE_WHILE_SERVICE_CONNECTED_ERROR = (
    "CANNOT_DELETE_PROFILE_WHILE_SERVICE_CONNECTED_ERROR"
)

# Youth Profile specific errors
CANNOT_RENEW_YOUTH_PROFILE_ERROR = "CANNOT_RENEW_YOUTH_PROFILE_ERROR"
CANNOT_SET_PHOTO_USAGE_PERMISSION_IF_UNDER_15_YEARS_ERROR = (
    "CANNOT_SET_PHOTO_USAGE_PERMISSION_IF_UNDER_15_YEARS_ERROR"
)
