# Generated by Django 2.2.3 on 2019-08-26 07:48
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("profiles", "0007_add_legal_relationship_model")]

    operations = [
        migrations.CreateModel(
            name="YouthProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ssn", models.CharField(max_length=11)),
                ("school_name", models.CharField(max_length=128)),
                ("school_class", models.CharField(max_length=10)),
                ("expiration", models.DateField(default=datetime.date.today)),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("fi", "Finnish"),
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("so", "Somali"),
                            ("ar", "Arabic"),
                            ("et", "Estonian"),
                            ("ru", "Russian"),
                        ],
                        default="fi",
                        max_length=32,
                    ),
                ),
                ("volunteer_info", models.TextField(blank=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("dont_know", "Don't know"),
                            ("rather_not_say", "Rather not say"),
                        ],
                        max_length=32,
                    ),
                ),
                ("diabetes", models.BooleanField(default=False)),
                ("epilepsy", models.BooleanField(default=False)),
                ("heart_disease", models.BooleanField(default=False)),
                ("extra_illnesses_info", models.TextField(blank=True)),
                ("serious_allergies", models.BooleanField(default=False)),
                ("allergies", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_time",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("photo_usage_approved", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_youth_profiles",
                        to="profiles.Profile",
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youth_profile",
                        to="profiles.Profile",
                    ),
                ),
            ],
        )
    ]
