# Generated by Django 2.2.3 on 2019-10-23 07:37

from django.db import migrations, models
import django.db.models.deletion
import uuid
import youths.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("profiles", "0008_remove_profile_add_basic_profile")]

    operations = [
        migrations.CreateModel(
            name="YouthProfile",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("school_name", models.CharField(max_length=128)),
                ("school_class", models.CharField(max_length=10)),
                (
                    "expiration",
                    models.DateField(default=youths.models.calculate_expiration),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("fi", "Finnish"),
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("so", "Somali"),
                            ("ar", "Arabic"),
                            ("et", "Estonian"),
                            ("ru", "Russian"),
                        ],
                        default="fi",
                        max_length=32,
                    ),
                ),
                ("volunteer_info", models.TextField(blank=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("dont_know", "Don't know"),
                            ("rather_not_say", "Rather not say"),
                        ],
                        max_length=32,
                    ),
                ),
                ("diabetes", models.BooleanField(default=False)),
                ("epilepsy", models.BooleanField(default=False)),
                ("heart_disease", models.BooleanField(default=False)),
                ("extra_illnesses_info", models.TextField(blank=True)),
                ("serious_allergies", models.BooleanField(default=False)),
                ("allergies", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("approver_email", models.EmailField(max_length=254)),
                (
                    "approval_token",
                    models.CharField(
                        blank=True, default=uuid.uuid4, editable=False, max_length=36
                    ),
                ),
                (
                    "approval_notification_timestamp",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "approved_time",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("photo_usage_approved", models.BooleanField(default=False)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youth_profile",
                        to="profiles.BasicProfile",
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
