# Generated by Django 2.2.3 on 2019-11-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("youths", "0002_change_approver_fields")]

    operations = [
        migrations.RenameField(
            model_name="youthprofile",
            old_name="preferred_language",
            new_name="language_at_home",
        ),
        migrations.RemoveField(model_name="youthprofile", name="allergies"),
        migrations.RemoveField(model_name="youthprofile", name="diabetes"),
        migrations.RemoveField(model_name="youthprofile", name="epilepsy"),
        migrations.RemoveField(model_name="youthprofile", name="extra_illnesses_info"),
        migrations.RemoveField(model_name="youthprofile", name="gender"),
        migrations.RemoveField(model_name="youthprofile", name="heart_disease"),
        migrations.RemoveField(model_name="youthprofile", name="notes"),
        migrations.RemoveField(model_name="youthprofile", name="serious_allergies"),
        migrations.RemoveField(model_name="youthprofile", name="ssn"),
        migrations.RemoveField(model_name="youthprofile", name="volunteer_info"),
        migrations.AddField(
            model_name="youthprofile",
            name="approver_first_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="youthprofile",
            name="approver_last_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="youthprofile",
            name="approver_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
