# Generated by Django 2.2.4 on 2019-11-13 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("youths", "0005_post_profile_uuid")]

    operations = [
        migrations.AddField(
            model_name="youthprofile",
            name="birth_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        )
    ]
