# Generated by Django 2.2.4 on 2019-12-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("youths", "0007_fix_enums")]

    operations = [
        migrations.AlterField(
            model_name="youthprofile",
            name="approver_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="youthprofile",
            name="photo_usage_approved",
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name="youthprofile",
            name="school_class",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="youthprofile",
            name="school_name",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
