# Generated by Django 2.2.10 on 2020-04-23 12:36

from django.db import migrations, models


def generate_membership_numbers(apps, schema_editor):
    """Generate membership numbers for YouthProfile which are missing it."""
    YouthProfile = apps.get_model("youths", "YouthProfile")
    for profile in YouthProfile.objects.all():
        membership_number = str(profile.pk).zfill(6)
        YouthProfile.objects.filter(pk=profile.pk).update(
            membership_number=membership_number
        )


class Migration(migrations.Migration):

    dependencies = [
        ("youths", "0008_change_required_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="youthprofile",
            name="membership_number",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.RunPython(generate_membership_numbers, migrations.RunPython.noop),
    ]
