# Generated by Django 2.2.13 on 2021-02-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("youths", "0010_additionalcontactperson"),
    ]

    operations = [
        migrations.DeleteModel(name="AdditionalContactPerson",),
    ]
