# Generated by Django 2.2.13 on 2021-02-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("youths", "0011_delete_additionalcontactperson"),
    ]

    operations = [
        migrations.DeleteModel(name="YouthProfile",),
    ]
