# Generated by Django 2.0.5 on 2018-07-04 07:10

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("fi", "Finnish"),
                            ("en", "English"),
                            ("sv", "Swedish"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "contact_method",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")], max_length=30
                    ),
                ),
                (
                    "preferences",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "concepts_of_interest",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
