# Generated by Django 2.0.5 on 2018-09-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0004_set_default_language_and_contact_method")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="nickname",
            field=models.CharField(blank=True, max_length=32, null=True),
        )
    ]
