# Generated by Django 2.2.3 on 2019-10-23 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("profiles", "0008_remove_profile_add_basic_profile")]

    operations = [
        migrations.CreateModel(
            name="LegalRelationship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("custody", "Custodianship")],
                        default="custody",
                        max_length=30,
                    ),
                ),
                (
                    "confirmation_degree",
                    models.CharField(
                        choices=[
                            ("none", "Not authenticated"),
                            ("strong", "Strong authentication (Suomi.fi)"),
                            ("id_shown", "Guardian present"),
                            ("proxy", "Approved via signed document"),
                        ],
                        default="none",
                        max_length=30,
                    ),
                ),
                ("expiration", models.DateField(blank=True, null=True)),
                (
                    "representative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="representatives",
                        to="profiles.BasicProfile",
                    ),
                ),
                (
                    "representee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="representees",
                        to="profiles.BasicProfile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="basicprofile",
            name="legal_relationships",
            field=models.ManyToManyField(
                through="profiles.LegalRelationship", to="profiles.BasicProfile"
            ),
        ),
    ]
