# Generated by Django 2.2.4 on 2019-11-06 07:17

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("profiles", "0008_add_first_name_and_last_name_to_profile")]

    operations = [
        migrations.CreateModel(
            name="SensitiveData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ssn", encrypted_fields.fields.EncryptedCharField(max_length=11)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.Profile",
                    ),
                ),
            ],
        )
    ]
