# Generated by Django 2.2.4 on 2019-11-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_sensitivedata"),
        ("profiles", "0010_switch_profile_to_uuid"),
    ]

    operations = []
