# Generated by Django 2.2.4 on 2019-11-13 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("profiles", "0011_merge_20191112_1632")]

    operations = [
        migrations.RemoveField(model_name="profile", name="email"),
        migrations.RemoveField(model_name="profile", name="phone"),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary", models.BooleanField(default=False)),
                ("phone", models.CharField(max_length=255, null=True)),
                (
                    "phone_type",
                    models.CharField(
                        choices=[
                            ("", ""),
                            ("WORK", "Work phone"),
                            ("HOME", "Home phone"),
                            ("MOBILE", "Mobile phone"),
                            ("OTHER", "Other phone"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="profiles.Profile",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary", models.BooleanField(default=False)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("", ""),
                            ("WORK", "Work email"),
                            ("PERSONAL", "Personal email"),
                            ("OTHER", "Other email"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="profiles.Profile",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary", models.BooleanField(default=False)),
                ("address", models.CharField(max_length=128)),
                ("postal_code", models.CharField(max_length=5)),
                ("city", models.CharField(max_length=64)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("", ""),
                            ("WORK", "Work address"),
                            ("HOME", "Home address"),
                            ("OTHER", "Other address"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="profiles.Profile",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
