# Generated by Django 2.2.4 on 2019-11-19 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("profiles", "0012_create_contact_20191113_0926")]

    operations = [
        migrations.RemoveField(model_name="sensitivedata", name="profile"),
        migrations.AddField(
            model_name="sensitivedata",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.Profile"
            ),
        ),
    ]
