# Generated by Django 2.2.8 on 2020-01-02 12:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [("profiles", "0015_change_required_fields")]

    operations = [
        migrations.CreateModel(
            name="ClaimToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True, default=uuid.uuid4, editable=False, max_length=36
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_tokens",
                        to="profiles.Profile",
                    ),
                ),
            ],
        )
    ]
