# Generated by Django 2.2.8 on 2020-01-09 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("profiles", "0018_auto_20200109_1336")]

    operations = [migrations.RemoveField(model_name="profile", name="preferences")]
