# Generated by Django 2.2.8 on 2020-03-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("profiles", "0019_remove_profile_preferences")]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="phone",
            name="phone",
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="language",
            field=models.CharField(
                choices=[("fi", "Finnish"), ("en", "English"), ("sv", "Swedish")],
                db_index=True,
                default="fi",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="nickname",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
