# Generated by Django 2.2.10 on 2020-05-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0023_remove_newsletter_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(name="email", options={"ordering": ["-primary"]},),
    ]
