# Generated by Django 2.2.10 on 2020-04-17 14:13

from django.db import migrations, models
import django.db.models.deletion


def populate_primary_email(apps, schema_editor):
    """
    Goes through all the profiles:
    1) Tries to set first matching email with primary=True as a primary email
    2) Tries to set first email as a primary email
    3) If no emails found, profile gets deleted with a message
    """
    Profile = apps.get_model("profiles", "Profile")
    for profile in Profile.objects.all():
        primary_email = profile.emails.filter(primary=True).first()
        if not primary_email:
            if profile.emails.count() > 0:
                primary_email = profile.emails.first()
            else:
                print(f"Removing profile of {profile.first_name} {profile.last_name}\n")
                profile.delete()
                continue
        profile.primary_email = primary_email
        profile.save()


class Migration(migrations.Migration):

    dependencies = [("profiles", "0023_remove_newsletter_fields")]

    operations = [
        migrations.AlterUniqueTogether(
            name="email", unique_together={("id", "profile")}
        ),
        migrations.AddField(
            model_name="profile",
            name="primary_email",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_email_profile",
                to="profiles.Email",
            ),
        ),
        migrations.RunPython(populate_primary_email, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="profile",
            name="primary_email",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_email_profile",
                to="profiles.Email",
            ),
        ),
    ]
