# Generated by Django 2.2.13 on 2020-09-30 08:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import profiles.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0026_email_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryReadAccessToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "validity_duration",
                    models.DurationField(
                        default=profiles.models._default_temporary_read_access_token_validity_duration
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_access_tokens",
                        to="profiles.Profile",
                    ),
                ),
            ],
        ),
    ]
