# Generated by Django 2.2.13 on 2020-11-04 07:52

from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0027_temporaryreadaccesstoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerifiedPersonalInformation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, max_length=1024
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verified_personal_information",
                        to="profiles.Profile",
                    ),
                ),
            ],
        ),
    ]
