# Generated by Django 2.2.13 on 2020-11-04 07:55

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0028_verifiedpersonalinformation"),
    ]

    operations = [
        migrations.AddField(
            model_name="verifiedpersonalinformation",
            name="email",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=1024
            ),
        ),
        migrations.AddField(
            model_name="verifiedpersonalinformation",
            name="given_name",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=1024
            ),
        ),
        migrations.AddField(
            model_name="verifiedpersonalinformation",
            name="last_name",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=1024
            ),
        ),
        migrations.AddField(
            model_name="verifiedpersonalinformation",
            name="municipality_of_residence",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=1024
            ),
        ),
        migrations.AddField(
            model_name="verifiedpersonalinformation",
            name="municipality_of_residence_number",
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="verifiedpersonalinformation",
            name="national_identification_number",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=1024
            ),
        ),
    ]
