# Generated by Django 2.2.13 on 2020-11-10 11:17

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0029_auto_20201104_0955"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerifiedPersonalInformationPermanentAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "street_address",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, max_length=1024
                    ),
                ),
                (
                    "postal_code",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, max_length=1024
                    ),
                ),
                (
                    "post_office",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, max_length=1024
                    ),
                ),
                (
                    "verified_personal_information",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permanent_address",
                        to="profiles.VerifiedPersonalInformation",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
