# Generated by Django 2.2.13 on 2020-11-12 09:38

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0031_verifiedpersonalinformationtemporaryaddress"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerifiedPersonalInformationPermanentForeignAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "street_address",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, max_length=1024
                    ),
                ),
                (
                    "additional_address",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, max_length=1024
                    ),
                ),
                (
                    "country_code",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, max_length=3
                    ),
                ),
                (
                    "verified_personal_information",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permanent_foreign_address",
                        to="profiles.VerifiedPersonalInformation",
                    ),
                ),
            ],
        ),
    ]
