# Generated by Django 2.2.13 on 2021-02-03 07:03

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0033_auto_20201113_1515"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verifiedpersonalinformation",
            name="email",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, help_text="Email.", max_length=1024
            ),
        ),
        migrations.AlterField(
            model_name="verifiedpersonalinformation",
            name="first_name",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, help_text="First name(s).", max_length=1024
            ),
        ),
        migrations.AlterField(
            model_name="verifiedpersonalinformation",
            name="given_name",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True,
                help_text="The name the person is called with.",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="verifiedpersonalinformation",
            name="last_name",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, help_text="Last name.", max_length=1024
            ),
        ),
        migrations.AlterField(
            model_name="verifiedpersonalinformation",
            name="municipality_of_residence",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True,
                help_text="Official municipality of residence in Finland as a free form text.",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="verifiedpersonalinformation",
            name="municipality_of_residence_number",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True,
                help_text="Official municipality of residence in Finland as an official number.",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="verifiedpersonalinformation",
            name="national_identification_number",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True,
                help_text="Finnish national identification number.",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="verifiedpersonalinformationpermanentforeignaddress",
            name="additional_address",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True,
                help_text="Additional address information, perhaps town, county, state, country etc.",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="verifiedpersonalinformationpermanentforeignaddress",
            name="country_code",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, help_text="An ISO 3166-1 country code.", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="verifiedpersonalinformationpermanentforeignaddress",
            name="street_address",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True,
                help_text="Street address or whatever is the _first part_ of the address.",
                max_length=1024,
            ),
        ),
    ]
