# Generated by Django 2.2.13 on 2021-04-09 09:44

from django.db import migrations
import encrypted_fields.fields
import utils.fields
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0038_start_using_searchable_national_identification_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verifiedpersonalinformation",
            name="_national_identification_number_data",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=1024
            ),
        ),
        migrations.AlterField(
            model_name="verifiedpersonalinformation",
            name="national_identification_number",
            field=utils.fields.CallableHashKeyEncryptedSearchField(
                blank=True,
                db_index=True,
                encrypted_field_name="_national_identification_number_data",
                hash_key=profiles.models.get_national_identification_number_hash_key,
                help_text="Finnish national identification number.",
                max_length=66,
                null=True,
            ),
        ),
    ]
