# Generated by Django 2.2.20 on 2021-05-07 07:58

import encrypted_fields.fields
from django.db import migrations

import profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0041_shorten_vpi_text_field_max_lengths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verifiedpersonalinformation",
            name="_national_identification_number_data",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True,
                max_length=1024,
                validators=[
                    profiles.validators.validate_finnish_national_identification_number
                ],
            ),
        ),
    ]
