# Generated by Django 2.2.22 on 2021-05-12 07:24

from django.db import migrations
import encrypted_fields.fields
import profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0042_add_validator_to_vpi_national_identification_number_field__noop",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="verifiedpersonalinformation",
            name="municipality_of_residence_number",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True,
                help_text="Official municipality of residence in Finland as an official number.",
                max_length=3,
                validators=[
                    profiles.validators.validate_finnish_municipality_of_residence_number
                ],
            ),
        ),
    ]
