# Generated by Django 2.2.24 on 2021-09-13 12:44

import encrypted_fields.fields
from django.db import migrations

import profiles.validators


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0048_change_phone_number_to_not_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensitivedata",
            name="ssn",
            field=encrypted_fields.fields.EncryptedCharField(
                max_length=11,
                validators=[
                    profiles.validators.validate_finnish_national_identification_number
                ],
            ),
        ),
    ]
