# Generated by Django 2.2.24 on 2021-09-24 07:21

from django.db import migrations

import utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0049_add_validator_to_sensitivedata__noop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=utils.fields.NullToEmptyCharField(
                blank=True, db_index=True, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=utils.fields.NullToEmptyCharField(
                blank=True, db_index=True, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="nickname",
            field=utils.fields.NullToEmptyCharField(
                blank=True, db_index=True, max_length=32
            ),
        ),
    ]
