# Generated by Django 2.2.24 on 2021-11-04 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0051_address_fields_blank_and_country_code_validator__noop"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="image"),
    ]
