# Generated by Django 2.2.24 on 2021-11-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0052_remove_image_field_from_profile"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="legal_relationships"),
        migrations.DeleteModel(name="LegalRelationship"),
    ]
