# Generated by Django 2.2.25 on 2021-12-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0054_remove_profile_concepts_of_interest"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="divisions_of_interest"),
        migrations.DeleteModel(name="DivisionOfInterest"),
    ]
