# Generated by Django 2.2.25 on 2022-01-11 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0055_remove_divisions_of_interest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address", options={"ordering": ["-primary", "id"]}
        ),
        migrations.AlterModelOptions(
            name="email", options={"ordering": ["-primary", "id"]}
        ),
        migrations.AlterModelOptions(
            name="phone", options={"ordering": ["-primary", "id"]}
        ),
        migrations.AlterModelOptions(name="profile", options={"ordering": ["id"]}),
    ]
