# Generated by Django 4.2.9 on 2024-04-17 10:00

from django.db import migrations
from django.db.models.functions import Substr

import utils.fields


def truncate_name_fields(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    Profile.objects.update(
        first_name=Substr("first_name", 1, 150), last_name=Substr("last_name", 1, 150)
    )


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0057_remove_profile_id_default_value__noop"),
    ]

    operations = [
        migrations.RunPython(truncate_name_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=utils.fields.NullToEmptyCharField(
                blank=True, db_index=True, max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=utils.fields.NullToEmptyCharField(
                blank=True, db_index=True, max_length=150
            ),
        ),
    ]
