# Generated by Django 3.2.16 on 2022-11-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_first_name_max_length_to_150"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_system_user",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user represents another system instead of a human being.",
                verbose_name="system user status",
            ),
        ),
    ]
