# Generated by Django 2.2.4 on 2019-11-08 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_switch_profile_to_uuid"),
        ("services", "0004_post_profile_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("HKI_MY_DATA", "HKI_MY_DATA"),
                    ("BERTH", "BERTH"),
                    ("YOUTH_MEMBERSHIP", "YOUTH_MEMBERSHIP"),
                    ("GODCHILDREN_OF_CULTURE", "GODCHILDREN_OF_CULTURE"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
        migrations.AlterUniqueTogether(name="service", unique_together=set()),
        migrations.RemoveField(model_name="service", name="profile"),
        migrations.CreateModel(
            name="ServiceConnection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.Profile",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="services.Service",
                    ),
                ),
            ],
            options={"unique_together": {("profile", "service")}},
        ),
    ]
