# Generated by Django 2.2.8 on 2020-01-27 13:24

import django.db.models.deletion
import parler.models
from django.db import migrations, models

import services.models


class Migration(migrations.Migration):
    dependencies = [("services", "0008_servicetranslation")]

    operations = [
        migrations.CreateModel(
            name="AllowedDataField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=30)),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=services.models.get_next_data_field_order,
                        editable=False,
                    ),
                ),
            ],
            options={"ordering": ["order"]},
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name="service",
            name="allowed_data_fields",
            field=models.ManyToManyField(to="services.AllowedDataField"),
        ),
        migrations.CreateModel(
            name="AllowedDataFieldTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("label", models.CharField(max_length=64)),
                (
                    "master",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="services.AllowedDataField",
                    ),
                ),
            ],
            options={
                "verbose_name": "allowed data field Translation",
                "db_table": "services_alloweddatafield_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
        ),
    ]
