# Generated by Django 2.2.10 on 2020-05-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0010_add_sensitivedata_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alloweddatafield",
            name="field_name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
