# Generated by Django 2.2.10 on 2020-05-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("services", "0011_make_alloweddatafield_field_name_unique")]

    operations = [
        migrations.AddField(
            model_name="service",
            name="gdpr_url",
            field=models.URLField(
                blank=True,
                help_text="Enter the URL of the service. "
                "Final URLs are generated by concatenating the url with the profile UUID.",
                max_length=2000,
            ),
        )
    ]
