# Generated by Django 2.2.10 on 2020-05-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0011_make_alloweddatafield_field_name_unique"),
        ("services", "0011_add_gdpr_url"),
    ]

    operations = []
