# Generated by Django 2.2.10 on 2020-06-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0012_add_gdpr_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="gdpr_delete_scope",
            field=models.CharField(
                blank=True, help_text="GDPR API delete operation scope", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="gdpr_query_scope",
            field=models.CharField(
                blank=True, help_text="GDPR API query operation scope", max_length=200
            ),
        ),
    ]
