# Generated by Django 2.2.13 on 2020-12-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0013_add_gdpr_api_scopes_to_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="gdpr_url",
            field=models.CharField(
                blank=True,
                help_text="Enter the URL of the service. "
                "Final URLs are generated by concatenating the url with the profile UUID.",
                max_length=2000,
            ),
        ),
    ]
