# Generated by Django 2.2.13 on 2021-02-01 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0014_change_gdpr_url_to_charfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceClientId",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=256, unique=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_ids",
                        to="services.Service",
                    ),
                ),
            ],
        ),
    ]
