# Generated by Django 2.2.13 on 2021-02-22 16:56

import enumfields.fields
from django.db import migrations

import services.enums


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0016_add_name_field_to_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="service_type",
            field=enumfields.fields.EnumField(
                enum=services.enums.ServiceType, max_length=32, null=True, unique=True
            ),
        ),
    ]
