# Generated by Django 2.2.13 on 2021-03-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0017_make_service_type_field_nullable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "permissions": (
                    ("can_manage_profiles", "Can manage profiles"),
                    ("can_view_profiles", "Can view profiles"),
                    ("can_manage_sensitivedata", "Can manage sensitive data"),
                    ("can_view_sensitivedata", "Can view sensitive data"),
                    (
                        "can_view_verified_personal_information",
                        "Can view verified personal information",
                    ),
                )
            },
        ),
    ]
