# Generated by Django 2.2.24 on 2021-10-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0019_service_implicit_connection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="gdpr_url",
            field=models.CharField(
                blank=True,
                help_text="The URL of the Service's GDPR endpoint. "
                'Tokens "$profile_id" or "$user_uuid" will be replaced with the corresponding value. '
                "Otherwise the Profile ID will be automatically appended to the url.",
                max_length=2000,
            ),
        ),
    ]
