# Generated by Django 2.2.25 on 2022-01-11 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0022_remove_service_implicit_connection"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["id"],
                "permissions": (
                    ("can_manage_profiles", "Can manage profiles"),
                    ("can_view_profiles", "Can view profiles"),
                    ("can_manage_sensitivedata", "Can manage sensitive data"),
                    ("can_view_sensitivedata", "Can view sensitive data"),
                    (
                        "can_view_verified_personal_information",
                        "Can view verified personal information",
                    ),
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="serviceconnection", options={"ordering": ["id"]}
        ),
    ]
