# Generated by Django 3.2.11 on 2022-01-13 12:18

import django.db.models.deletion
import parler.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0023_change_ordering__noop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alloweddatafieldtranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="services.alloweddatafield",
            ),
        ),
        migrations.AlterField(
            model_name="servicetranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="services.service",
            ),
        ),
    ]
