# Generated by Django 3.2.11 on 2022-02-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0024_parler_field_type_change"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicetranslation",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
