# Generated by Django 3.2.19 on 2023-08-25 06:17

import enumfields.fields
from django.db import migrations, models

import services.enums
import services.models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0025_increase_service_description_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="gdpr_audience",
            field=models.CharField(
                blank=True,
                help_text="Audience of the GDPR API. Must be filled if the API accepts tokens from Keycloak",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="idp",
            field=services.models.ChoiceArrayField(
                base_field=enumfields.fields.EnumField(
                    enum=services.enums.ServiceIdp, max_length=32
                ),
                blank=True,
                help_text="Identity providers the service supports. Tunnistamo is implied If none selected.",
                null=True,
                size=None,
            ),
        ),
    ]
