# Generated by Django 3.2.19 on 2023-08-25 06:17

import enumfields.fields
from django import forms
from django.contrib.postgres.fields import ArrayField
from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class ChoiceArrayField(ArrayField):
    """Arrayfield where the widget in model forms (e.g. in the admin) is changed

    The default widget for ArrayField is a simple text input. This modification
    changes the widget to multiple checkboxes.

    from https://stackoverflow.com/a/66059615"""

    def formfield(self, **kwargs):
        kwargs.update(
            {
                "form_class": forms.TypedMultipleChoiceField,
                "choices": self.base_field.choices,
                "coerce": self.base_field.to_python,
                "widget": forms.CheckboxSelectMultiple,
            }
        )
        return super(ArrayField, self).formfield(**kwargs)


class ServiceIdp(enumfields.Enum):
    TUNNISTAMO = "tunnistamo"
    KEYCLOAK = "keycloak"

    class Labels:
        TUNNISTAMO = _("Tunnistamo")
        KEYCLOAK = _("Keycloak")


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0025_increase_service_description_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="gdpr_audience",
            field=models.CharField(
                blank=True,
                help_text="Audience of the GDPR API. Must be filled if the API accepts tokens from Keycloak",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="idp",
            field=ChoiceArrayField(
                base_field=enumfields.fields.EnumField(enum=ServiceIdp, max_length=32),
                blank=True,
                help_text="Identity providers the service supports. Tunnistamo is implied If none selected.",
                null=True,
                size=None,
            ),
        ),
    ]
