# Generated by Django 4.2.9 on 2024-04-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0026_add_idp_and_gdpr_audience_to_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetranslation",
            name="privacy_policy_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicetranslation",
            name="terms_of_use_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
