# Generated by Django 4.2.18 on 2025-03-31 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0027_servicetranslation_privacy_policy_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="idp",
        ),
    ]
