# Generated by Django 2.2.10 on 2020-05-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptiontype",
            name="code",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="subscriptiontypecategory",
            name="code",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
