# Generated by Django 2.2.24 on 2021-12-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_subscription_type_and_category_unique"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptiontype", name="subscription_type_category",
        ),
        migrations.AlterUniqueTogether(
            name="subscriptiontypecategorytranslation", unique_together=None,
        ),
        migrations.RemoveField(
            model_name="subscriptiontypecategorytranslation", name="master",
        ),
        migrations.AlterUniqueTogether(
            name="subscriptiontypetranslation", unique_together=None,
        ),
        migrations.RemoveField(
            model_name="subscriptiontypetranslation", name="master",
        ),
        migrations.DeleteModel(name="Subscription",),
        migrations.DeleteModel(name="SubscriptionType",),
        migrations.DeleteModel(name="SubscriptionTypeCategory",),
        migrations.DeleteModel(name="SubscriptionTypeCategoryTranslation",),
        migrations.DeleteModel(name="SubscriptionTypeTranslation",),
    ]
