= Configuration
:toc: preamble

The service can be configured by setting various environment variables.

== Standard Django configuration

The following environment variables set directly the https://docs.djangoproject.com/en/2.2/ref/settings/[Django setting] with the same name:

- https://docs.djangoproject.com/en/2.2/ref/settings/#allowed-hosts[`ALLOWED_HOSTS`]. Default is empty list.
- https://docs.djangoproject.com/en/2.2/ref/settings/#csrf-cookie-name[`CSRF_COOKIE_NAME`]. Default is to use the Django default.
- https://docs.djangoproject.com/en/2.2/ref/settings/#csrf-cookie-path[`CSRF_COOKIE_PATH`]. Default is to use the Django default.
- https://docs.djangoproject.com/en/2.2/ref/settings/#csrf-cookie-secure[`CSRF_COOKIE_SECURE`]. Default is to use the Django default.
- https://docs.djangoproject.com/en/2.2/ref/settings/#csrf-trusted-origins[`CSRF_TRUSTED_ORIGINS`]. Default is empty list.
- https://docs.djangoproject.com/en/2.2/ref/settings/#debug[`DEBUG`]. Default is `True`.
- https://docs.djangoproject.com/en/2.2/ref/settings/#default-from-email[`DEFAULT_FROM_EMAIL`]. Default is "\no-reply@hel.fi". See also the other <<Email,email>> settings.
- https://docs.djangoproject.com/en/2.2/ref/settings/#force-script-name[`FORCE_SCRIPT_NAME`]. Default is to use the Django default.
- https://docs.djangoproject.com/en/2.2/ref/settings/#media-url[`MEDIA_URL`]. Default is "/media/".
- https://docs.djangoproject.com/en/2.2/ref/settings/#secret-key[`SECRET_KEY`]. If `DEBUG` is `True`, default is "xxx", otherwise empty string (which prevents Django from starting, so you need to set this).
- https://docs.djangoproject.com/en/2.2/ref/settings/#session-cookie-name[`SESSION_COOKIE_NAME`]. Default is to use the Django default.
- https://docs.djangoproject.com/en/2.2/ref/settings/#session-cookie-path[`SESSION_COOKIE_PATH`]. Default is to use the Django default.
- https://docs.djangoproject.com/en/2.2/ref/settings/#session-cookie-secure[`SESSION_COOKIE_SECURE`]. Default is to use the Django default.
- https://docs.djangoproject.com/en/2.2/ref/settings/#static-url[`STATIC_URL`]. Default is "/static/".
- https://docs.djangoproject.com/en/2.2/ref/settings/#use-x-forwarded-host[`USE_X_FORWARDED_HOST`]. Default is to use the Django default.

The following environment variables can be used to affect some standard Django settings, but somewhat indirectly:

- `CACHE_URL`: Configures the https://docs.djangoproject.com/en/2.2/ref/settings/#caches["default" cache] using https://django-environ.readthedocs.io[Django-environ]. Default is "locmemcache://".
- `DATABASE_URL`: Configures the https://docs.djangoproject.com/en/2.2/ref/settings/#databases["default" database connection] using https://django-environ.readthedocs.io[Django-environ]. Default is "postgres://open_city_profile:open_city_profile@localhost/open_city_profile".
- `EMAIL_URL`: Configures email for Django using https://django-environ.readthedocs.io/en/latest/#email-settings[Django-environ]. Default is "consolemail://".
- `VAR_ROOT`: Provides a base path for the https://docs.djangoproject.com/en/2.2/ref/settings/#media-root[`MEDIA_ROOT`] and https://docs.djangoproject.com/en/2.2/ref/settings/#static-root[`STATIC_ROOT`] Django settings. `MEDIA_ROOT` will be set to `${VAR_ROOT}/media` and `STATIC_ROOT` to `${VAR_ROOT}/static`. If run with Docker (determined by checking that the project is in an `/app` directory), `VAR_ROOT` defaults to `/var`. Otherwise it defaults to a path called `var` under the project directory.

== Authentication and authorization

This project uses https://github.com/City-of-Helsinki/django-helusers[Django-helusers] for doing authentication. The following environment variables correspond directly to Django-helusers settings:

- `TOKEN_AUTH_ACCEPTED_AUDIENCE`: Corresponds to `OIDC_API_TOKEN_AUTH.AUDIENCE`. Default is empty.
- `TOKEN_AUTH_ACCEPTED_SCOPE_PREFIX`: Corresponds to `OIDC_API_TOKEN_AUTH. API_SCOPE_PREFIX`. Default is empty.
- `TOKEN_AUTH_REQUIRE_SCOPE`: Corresponds to `OIDC_API_TOKEN_AUTH. REQUIRE_API_SCOPE_FOR_AUTHENTICATION`. Default is `False`.

The following environment variables configure authentication or authorization in other ways:

- `TOKEN_AUTH_AUTHSERVER_URL`: Sets the "main" authentication server's URL. The URL needs to be exactly what the authentication server reports as its `issuer` value. Default is empty.
- `ADDITIONAL_AUTHSERVER_URLS`: Sets additional authentication server URLs as a list of strings. JWTs signed by these servers are accepted for authentication. The URLs need to be exactly what the authentication servers report as their `issuer` value. Default is empty list.
- `VERIFIED_PERSONAL_INFORMATION_ACCESS_AMR_LIST`: Can be used to limit staff users access to verified personal information fields for only those that have authenticated using certain authentication method (Denoted by the "amr" claim in the authentication token). If empty, access is not limited. Default is empty list.

It's possible to configure open-city-profile to communicate with a https://www.keycloak.org/[Keycloak] instance. User data gets synchronised into the Keycloak instance. The Keycloak instance can simultaneously act as an authentication server but it doesn't have to. All the following settings are needed — if any are missing, then the communication with Keycloak feature is disabled.

- `KEYCLOAK_BASE_URL`: The base URL of the Keycloak server, including any configured context path.
- `KEYCLOAK_REALM`: The name of the https://www.keycloak.org/docs/latest/server_admin/#the-master-realm[Keycloak realm] to use.
- `KEYCLOAK_CLIENT_ID`: Authentication to the Keycloak instance happens https://www.keycloak.org/docs/latest/server_development/#authenticate-with-a-service-account[using a service account]. This is the client id.
- `KEYCLOAK_CLIENT_SECRET`: ...and this is the client secret.

== Application logging

Application logs are output to stderr.

- `OPEN_CITY_PROFILE_LOG_LEVEL`: sets logging level. Use any string representation of a https://docs.python.org/dev/library/logging.html#levels[Python logging level]. Default is "DEBUG" if Django's `DEBUG` setting is on, otherwise it's "INFO".

== Audit events

Profile data access produces audit events. Audit events may be output to multiple destinations. The destinations can be enabled individually. By default all outputs are disabled.

=== Database output

- `AUDIT_LOG_TO_DB_ENABLED`: enable audit logging to database by setting to `True`. Default is `False`.

=== Python logger output

Output as JSON using the https://docs.python.org/3/library/logging.html[Python logging module].

- `AUDIT_LOG_TO_LOGGER_ENABLED`: enable audit logging to logger by setting to `True`. Default is `False`.
- `AUDIT_LOG_LOGGER_FILENAME`: by default logger output is sent to `stdout`. It's possible to send the output to a file instead, by giving a filename with this setting. The filename may be randomized by including capital "X" characters in it. The "X"s get replaced by random characters.

== Database encryption

https://pypi.org/project/django-searchable-encrypted-fields[Django-searchable-encrypted-fields] library is used to encrypt some data in the database. Read that library's documentation to learn what needs to be considered when handling these encryption keys and other values.

- `FIELD_ENCRYPTION_KEYS`: Used to encrypt/decrypt some data in the database. Corresponds directly to the setting with same name in django-searchable-encrypted-fields. Must be set to a valid value.
- `SALT_NATIONAL_IDENTIFICATION_NUMBER`: Used as additional salt in calculating search keys for the national identification number field in Profile. Given as the `hash_key` argument to django-searchable-encrypted-fields's `SearchField` instance. If not given and `DEBUG` is `True`, defaults to "DEBUG_SALT".

== GDPR API

GDPR API functionality needs to communicate with an authentication server. The implementation uses https://github.com/City-of-Helsinki/tunnistamo[Tunnistamo] specific endpoints, so this works only with Tunnistamo.

All the following environment variables are required for the GDPR API functionality to work correctly.

First of all, `TOKEN_AUTH_AUTHSERVER_URL` is used as the authentication server, so that environment variable needs to point to the correct Tunnistamo instance.

- `OIDC_CLIENT_ID`: Client id to use in the authorization code flow.
- `OIDC_CLIENT_SECRET`: Client secret to use in the authorization code flow.
- `GDPR_AUTH_CALLBACK_URL`: Callback URL should be the same which is used by the UI for fetching OAuth/OIDC authorization token for using the GDPR API.
- `TUNNISTAMO_API_TOKENS_URL`: Tunnistamo URL from which the backend will fetch API tokens for GDPR API use.

== Feature flags

- `ENABLE_GRAPHIQL`: Enables GraphiQL testing user interface. If `DEBUG` is `True`, this setting has no effect and GraphiQL is always enabled. Default is `False`.
- `USE_X_FORWARDED_FOR`: Affects the way how a requester's IP address is figured out. If set to `True`, the `X-Forwarded-For` HTTP header is used as one option. Default is `False`.

== Sentry

It's possible to report errors to Sentry.

- `SENTRY_DSN`: Sets the https://docs.sentry.io/platforms/python/configuration/options/#dsn[Sentry DSN]. If this is not set, nothing is sent to Sentry.
- `SENTRY_ENVIRONMENT`: Sets the https://docs.sentry.io/platforms/python/configuration/options/#environment[Sentry environment]. Default is "development".
- `VERSION`: Sets the https://docs.sentry.io/platforms/python/configuration/options/#release[Sentry release]. See `VERSION` in <<Miscellaneous>>.

== Miscellaneous

- `VERSION`: Sets a version for the installation. Default is the output of `git describe --always` command, if it succeeds, otherwise `None`.
- `TEMPORARY_PROFILE_READ_ACCESS_TOKEN_VALIDITY_MINUTES`: For how long a temporary profile read access token is valid after creation. Value is in minutes. Default is 48 hours.
