name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  common:
    uses: City-of-Helsinki/.github/.github/workflows/ci-django-api.yml@main
    secrets: inherit
    with:
      python-version: 3.12
      postgres-major-version: 13
      extra-commands: |
        echo "Database sanitizer config"
        python manage.py check_sanitizerconfig
