name: Build & Production
on:
  push:
    tags:
      - 'release-*'

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW_STABLE }}
  BUILD_ARTIFACT_FOLDER: 'build_artifacts'
  SERVICE_ARTIFACT_FOLDER: 'service_artifacts'
  APP_MIGRATE_COMMAND: /app/.prod/on_deploy.sh
  SERVICE_PORT: "8080"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: andersinno/kolga-build-action@v2

  production:
    runs-on: ubuntu-latest
    needs: build
    name: Production
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2

      - name: Deploy
        uses: andersinno/kolga-deploy-action@v2
        with:
          track: 'stable'
        env:
          K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE_STABLE }}
          ENVIRONMENT_URL: https://${{ secrets.ENVIRONMENT_URL_STABLE }}
          K8S_SECRET_ALLOWED_HOSTS: "*"
          K8S_SECRET_DEBUG: 0
          K8S_SECRET_SECRET_KEY: ${{ secrets.GH_STABLE_DJANGO_SECRET_KEY }}
          K8S_SECRET_SENTRY_DSN: ${{ secrets.GH_SENTRY_DSN }}
          K8S_SECRET_SENTRY_ENVIRONMENT: "production"
          K8S_SECRET_SKIP_DATABASE_CHECK: 1
          K8S_SECRET_TOKEN_AUTH_ACCEPTED_AUDIENCE: "https://api.hel.fi/auth/helsinkiprofile"
          K8S_SECRET_TOKEN_AUTH_ACCEPTED_SCOPE_PREFIX: "helsinkiprofile"
          K8S_SECRET_TOKEN_AUTH_AUTHSERVER_URL: "https://api.hel.fi/sso/openid"
          K8S_SECRET_TOKEN_AUTH_REQUIRE_SCOPE: 1
          K8S_SECRET_OIDC_CLIENT_ID: ${{ secrets.GH_STABLE_OIDC_CLIENT_ID }}
          K8S_SECRET_OIDC_CLIENT_SECRET: ${{ secrets.GH_STABLE_OIDC_CLIENT_SECRET }}
          K8S_SECRET_TUNNISTAMO_API_TOKENS_URL: "https://api.hel.fi/sso/api-tokens"
          K8S_SECRET_GDPR_AUTH_CALLBACK_URL: "https://profiili.hel.fi/gdpr-callback"
          K8S_SECRET_VERSION: ${{ github.sha }}
          K8S_SECRET_MAIL_MAILGUN_KEY: ${{ secrets.GH_MAILGUN_API_KEY }}
          K8S_SECRET_MAIL_MAILGUN_DOMAIN: "mail.hel.ninja"
          K8S_SECRET_MAIL_MAILGUN_API: "https://api.eu.mailgun.net/v3"
          K8S_SECRET_MAILER_EMAIL_BACKEND: "anymail.backends.mailgun.EmailBackend"
          K8S_SECRET_DEFAULT_FROM_EMAIL: "no-reply@hel.ninja"
          K8S_SECRET_FIELD_ENCRYPTION_KEYS: ${{ secrets.GH_STABLE_FIELD_ENCRYPTION_KEYS }}
          K8S_SECRET_FORCE_SCRIPT_NAME: "/profiili"
          K8S_SECRET_MEDIA_URL: "/profiili/media/"
          K8S_SECRET_STATIC_URL: "/profiili/static/"
          K8S_SECRET_CSRF_COOKIE_NAME: "profiili-prod-csrftoken"
          K8S_SECRET_CSRF_COOKIE_PATH: "/profiili/"
          K8S_SECRET_CSRF_COOKIE_SECURE: 1
          K8S_SECRET_SESSION_COOKIE_NAME: "profiili-prod-sessionid"
          K8S_SECRET_SESSION_COOKIE_PATH: "/profiili/"
          K8S_SECRET_SESSION_COOKIE_SECURE: 1
          K8S_SECRET_USE_X_FORWARDED_HOST: 1
          K8S_SECRET_CSRF_TRUSTED_ORIGINS: "api.hel.fi"
          K8S_SECRET_DATABASE_HOST: ${{ secrets.K8S_SECRET_DATABASE_HOST_STABLE }}
          K8S_SECRET_DATABASE_URL: ${{ secrets.K8S_SECRET_DATABASE_URL_STABLE }}
          K8S_SECRET_DATABASE_PORT: ${{ secrets.K8S_SECRET_DATABASE_PORT_STABLE }}
          K8S_SECRET_DATABASE_DB: ${{ secrets.K8S_SECRET_DATABASE_DB_STABLE }}
          K8S_SECRET_DATABASE_USERNAME: ${{ secrets.K8S_SECRET_DATABASE_USERNAME_STABLE }}
          K8S_SECRET_DATABASE_PASSWORD: ${{ secrets.K8S_SECRET_DATABASE_PASSWORD_STABLE }}
